[project]
name = "what-is-love"
version = "0.1.0"
requires-python = ">=3.11"

[project.scripts]
what = "what.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["what.cli:main"]

[tool.hatch.build.targets.sdist]
include = ["src/what", "pyproject.toml", "README.md]

[project.optional-dependencies]
test = ["pytest"]
